import Fastify from 'fastify';
import cors from '@fastify/cors';
import staticPlugin from '@fastify/static';
import { createReadStream, existsSync, mkdirSync, readFileSync, statfsSync, statSync, writeFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { extname, isAbsolute, join, parse, relative, resolve } from 'node:path';
import { execFile, spawn } from 'node:child_process';
import { createConnection } from 'node:net';
import { promisify } from 'node:util';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from 'node:crypto';

type Rating = { profileId: string; mediaId: string; score: number; tags: string[]; at: string };
type ProfileRecord = { id:string; name:string; ageLimit:number; avatar:string; accent:string; pinHash?:string; createdAt:string };
type MediaMetadata = { provider:'tmdb'|'tvmaze'|'wikipedia'; providerId:number|string; title:string; originalTitle?:string; overview?:string; poster?:string; backdrop?:string; genres?:string[]; releaseDate?:string; ageRating?:string; runtime?:number; sourceUrl?:string; informationSource?:string };
type PlaybackEntry = { position:number; duration:number; updatedAt:string };
type Db = { profiles: ProfileRecord[]; library: LibraryItem[]; ratings: Rating[]; playback: Record<string, PlaybackEntry|number> };
type LibraryItem = { id: string; title: string; path: string; kind: 'film'|'serie'; year?: number; season?:number; episode?:number; size: number; modifiedAt:string; addedAt: string; technical?: Record<string,unknown>; metadata?:MediaMetadata };
type LibraryGroup = { id:string; title:string; year?:number; kind:'film'|'serie'; metadata?:MediaMetadata; versions:Array<Omit<LibraryItem,'path'>>; totalSize:number; episodeCount:number };
type Source = { id:string; name:string; url:string; apiKey:string; categories?:string };
type CatalogItem = { id:string; title:string; kind:'film'|'serie'; year:number; genres:string[]; duration:string; rating:number; quality:'1080p'; description:string; palette:[string,string]; symbol:string; art?:string; source:'tmdb'|'tvmaze'|'wikipedia'; sourceUrl?:string; informationSource?:string };
type CacheEntry<T> = { storedAt:string; expiresAt:number; data:T };
type CachedResult<T> = { data:T; cachedAt:string; state:'hit'|'miss'|'stale' };

const app = Fastify({ logger: true });
const port = Number(process.env.SCENEROOT_PORT ?? 4174);
const dataDir = resolve(process.env.SCENEROOT_DATA ?? './data');
const dbPath = join(dataDir, 'sceneroot.json');
const cacheDir = join(dataDir, 'cache');
const mediaRoots = (process.env.SCENEROOT_MEDIA ?? '/mnt/media').split(',').map(x => resolve(x.trim()));
const videoExt = new Set(['.mp4','.mkv','.webm','.avi','.mov','.m4v']);
const execFileAsync=promisify(execFile);
const videoMime:Record<string,string>={'.mp4':'video/mp4','.m4v':'video/mp4','.mkv':'video/x-matroska','.webm':'video/webm','.avi':'video/x-msvideo','.mov':'video/quicktime'};
function mimeFor(path:string){return videoMime[extname(path).toLowerCase()]??'application/octet-stream'}
function isWithin(root:string,path:string){const rel=relative(root,resolve(path));return rel!==''&&!rel.startsWith('..')&&!isAbsolute(rel)}
function isWithinRoots(path:string){return mediaRoots.some(root=>isWithin(root,path))}
const mpvSocket=process.env.SCENEROOT_MPV_IPC??(process.platform==='win32'?'\\\\.\\pipe\\sceneroot-mpv':'/tmp/sceneroot-mpv.sock');
let mpvProcess: ReturnType<typeof spawn> | null = null;
let mpvRequestId=0;
function mpvCommand<T=unknown>(command:unknown[]):Promise<T>{return new Promise((resolve,reject)=>{const requestId=++mpvRequestId;const socket=createConnection(mpvSocket);let buffer='';const timer=setTimeout(()=>{socket.destroy();reject(new Error('mpv IPC timeout'))},2500);const finish=(fn:()=>void)=>{clearTimeout(timer);socket.removeAllListeners();try{socket.end()}catch{}fn()};socket.on('connect',()=>socket.write(JSON.stringify({command,request_id:requestId})+'\n'));socket.on('data',chunk=>{buffer+=chunk.toString('utf8');let index;while((index=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,index).trim();buffer=buffer.slice(index+1);if(!line)continue;let message:{request_id?:number;error?:string;data?:unknown};try{message=JSON.parse(line)}catch{continue}if(message.request_id===requestId){if(message.error&&message.error!=='success')return finish(()=>reject(new Error(message.error)));return finish(()=>resolve(message.data as T))}}});socket.on('error',err=>{clearTimeout(timer);reject(err)})})}
async function mpvGet<T>(name:string):Promise<T|null>{try{return await mpvCommand<T>(['get_property',name])}catch{return null}}
function playbackEntry(value:unknown):PlaybackEntry|null{if(value==null)return null;if(typeof value==='number')return{position:value,duration:0,updatedAt:new Date(0).toISOString()};const v=value as Partial<PlaybackEntry>;return typeof v.position==='number'?{position:v.position,duration:Number(v.duration??0),updatedAt:String(v.updatedAt??new Date(0).toISOString())}:null}
mkdirSync(dataDir, { recursive: true });
mkdirSync(cacheDir, { recursive: true });

const pendingCacheRequests=new Map<string,Promise<CachedResult<unknown>>>();
function cachePath(key:string){return join(cacheDir,`${key.replace(/[^a-z0-9_-]/gi,'-')}.json`)}
function readCache<T>(key:string):CacheEntry<T>|null{try{return JSON.parse(readFileSync(cachePath(key),'utf8')) as CacheEntry<T>}catch{return null}}
async function cachedJson<T>(key:string,url:string,ttlMs:number):Promise<CachedResult<T>>{
  const cached=readCache<T>(key);const now=Date.now();if(cached&&cached.expiresAt>now)return{data:cached.data,cachedAt:cached.storedAt,state:'hit'};
  const running=pendingCacheRequests.get(key);if(running)return running as Promise<CachedResult<T>>;
  const request=(async()=>{try{const response=await fetch(url,{headers:{Accept:'application/json','User-Agent':'SceneRoot/0.1 (+https://github.com/sceneroot)'},signal:AbortSignal.timeout(12_000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const data=await response.json() as T;const entry:CacheEntry<T>={storedAt:new Date().toISOString(),expiresAt:Date.now()+ttlMs,data};writeFileSync(cachePath(key),JSON.stringify(entry));return{data,cachedAt:entry.storedAt,state:'miss'} as CachedResult<T>}catch(error){if(cached){app.log.warn({key,error},'Metadata provider unavailable; serving stale cache');return{data:cached.data,cachedAt:cached.storedAt,state:'stale'} as CachedResult<T>}throw error}finally{pendingCacheRequests.delete(key)}})();
  pendingCacheRequests.set(key,request as Promise<CachedResult<unknown>>);return request;
}

function loadDb(): Db {
  const empty:Db={ profiles: [], library: [], ratings: [], playback: {} };
  if (!existsSync(dbPath)) return empty;
  try { return {...empty,...JSON.parse(readFileSync(dbPath, 'utf8'))} as Db; } catch { return empty; }
}
function saveDb(db: Db) { writeFileSync(dbPath, JSON.stringify(db, null, 2)); }
function hashPin(pin:string){const salt=randomBytes(16);const digest=scryptSync(pin,salt,32);return`${salt.toString('hex')}:${digest.toString('hex')}`}
function verifyPin(pin:string,stored:string){try{const[saltHex,digestHex]=stored.split(':');const expected=Buffer.from(digestHex,'hex');const actual=scryptSync(pin,Buffer.from(saltHex,'hex'),expected.length);return timingSafeEqual(actual,expected)}catch{return false}}
function safeAvatar(value:string|undefined,fallback:string){return value&&(/^\/assets\/avatars\/[a-z0-9-]+\.png$/i.test(value)||/^[\p{L}\p{N}]$/u.test(value))?value:fallback}
function safeAccent(value:string|undefined){return value&&/^#[0-9a-f]{6}$/i.test(value)?value:'#22d3ee'}
function normalizeTmdb(item:Record<string,unknown>,kind:'movie'|'tv'):MediaMetadata{const title=String(kind==='tv'?item.name??item.original_name??'':item.title??item.original_title??'');const originalTitle=String(kind==='tv'?item.original_name??'':item.original_title??'');const releaseDate=String(kind==='tv'?item.first_air_date??'':item.release_date??'');const genres=Array.isArray(item.genres)?item.genres.map(g=>String((g as {name?:unknown}).name??'')).filter(Boolean):Array.isArray(item.genre_ids)?item.genre_ids.map(id=>tmdbGenres[Number(id)]).filter(Boolean):undefined;return{provider:'tmdb',providerId:Number(item.id),title,originalTitle,overview:String(item.overview??''),poster:item.poster_path?`https://image.tmdb.org/t/p/w500${item.poster_path}`:undefined,backdrop:item.backdrop_path?`https://image.tmdb.org/t/p/original${item.backdrop_path}`:undefined,genres,releaseDate,runtime:Number(item.runtime??0)||undefined,sourceUrl:`https://www.themoviedb.org/${kind==='tv'?'tv':'movie'}/${Number(item.id)}`}}
const tmdbGenres:Record<number,string>={12:'Aventure',14:'Fantastique',16:'Animation',18:'Drame',27:'Horreur',28:'Action',35:'Comédie',36:'Histoire',37:'Western',53:'Thriller',80:'Policier',99:'Documentaire',878:'Science-fiction',9648:'Mystère',10402:'Musique',10749:'Romance',10751:'Famille',10752:'Guerre',10759:'Action & aventure',10762:'Enfants',10763:'Actualités',10764:'Téléréalité',10765:'Science-fiction & fantastique',10766:'Soap',10767:'Talk-show',10768:'Guerre & politique',10770:'Téléfilm'};
function stripHtml(value:unknown){return String(value??'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
const tvmazeGenreNames:Record<string,string>={Adult:'Adulte',Adventure:'Aventure',Anime:'Anime',Children:'Enfants',Comedy:'Comédie',Crime:'Policier',DIY:'Bricolage',Drama:'Drame',Espionage:'Espionnage',Family:'Famille',Fantasy:'Fantastique',Food:'Cuisine',History:'Histoire',Horror:'Horreur',Legal:'Juridique',Medical:'Médical',Music:'Musique',Mystery:'Mystère',Nature:'Nature',Romance:'Romance','Science-Fiction':'Science-fiction',Sports:'Sport',Supernatural:'Surnaturel',Thriller:'Thriller',Travel:'Voyage',War:'Guerre',Western:'Western'};
function localizedTvmazeGenres(value:unknown){return Array.isArray(value)?value.map(genre=>tvmazeGenreNames[String(genre)]??String(genre)):[]}
function frenchTvmazeSummary(show:Record<string,unknown>){const premiered=String(show.premiered??'');const runtime=Number(show.averageRuntime??show.runtime??0);const statusNames:Record<string,string>={Running:'en cours',Ended:'terminée','To Be Determined':'au statut à confirmer','In Development':'en développement'};const typeNames:Record<string,string>={Scripted:'fiction',Reality:'téléréalité',Documentary:'documentaire',Animation:'animation',Variety:'divertissement',TalkShow:'talk-show',News:'actualité',Sports:'sport'};const network=show.network as {name?:string;country?:{code?:string}}|undefined;const webChannel=show.webChannel as {name?:string;country?:{code?:string}}|undefined;const code=network?.country?.code??webChannel?.country?.code;let country='';try{country=code?new Intl.DisplayNames(['fr'],{type:'region'}).of(code)??'':''}catch{}const parts=[`Série de ${typeNames[String(show.type??'')]??'télévision'}${country?` produite en ${country}`:''}${premiered?` et diffusée à partir de ${premiered.slice(0,4)}`:''}.`];if(runtime)parts.push(`Les épisodes durent environ ${runtime} minutes.`);const broadcaster=network?.name??webChannel?.name;if(broadcaster)parts.push(`Diffusion : ${broadcaster}.`);const status=statusNames[String(show.status??'')];if(status)parts.push(`La série est ${status}.`);parts.push('Le résumé narratif français n’est pas encore disponible.');return parts.join(' ')}
function durationLabel(minutes:unknown,kind:'film'|'serie'){const value=Number(minutes??0);if(!value)return kind==='serie'?'Série':'Durée inconnue';return`${Math.floor(value/60)}h${String(value%60).padStart(2,'0')}`}
function palette(id:number):[string,string]{const palettes:[string,string][]= [['#0e7490','#172554'],['#701a75','#1e40af'],['#065f46','#1e293b'],['#7c2d12','#581c87'],['#334155','#155e75']];return palettes[Math.abs(id)%palettes.length]}
function normalizeTmdbCatalog(item:Record<string,unknown>,kind:'film'|'serie'):CatalogItem{const title=String(kind==='serie'?item.name??item.original_name??'':item.title??item.original_title??'');const date=String(kind==='serie'?item.first_air_date??'':item.release_date??'');const id=Number(item.id);return{id:`tmdb-${kind}-${id}`,title,kind,year:Number(date.slice(0,4))||new Date().getFullYear(),genres:(Array.isArray(item.genre_ids)?item.genre_ids:[]).map(value=>tmdbGenres[Number(value)]).filter(Boolean),duration:kind==='serie'?'Série':'Durée inconnue',rating:Math.round(Number(item.vote_average??0)*10)/10,quality:'1080p',description:String(item.overview??''),palette:palette(id),symbol:kind==='serie'?'▥':'◉',art:item.backdrop_path?`https://image.tmdb.org/t/p/w780${item.backdrop_path}`:item.poster_path?`https://image.tmdb.org/t/p/w500${item.poster_path}`:undefined,source:'tmdb',sourceUrl:`https://www.themoviedb.org/${kind==='serie'?'tv':'movie'}/${id}`}}
type ProviderPage={items:CatalogItem[];hasMore:boolean;source:string;cachedAt:string;cacheState:string};
async function tmdbCatalog(kind:'film'|'serie',page:number,limit:number):Promise<ProviderPage>{const key=process.env.TMDB_API_KEY;if(!key)throw new Error('TMDB non configuré');const path=kind==='serie'?'tv':'movie';const url=new URL(`https://api.themoviedb.org/3/discover/${path}`);url.searchParams.set('api_key',key);url.searchParams.set('language','fr-FR');url.searchParams.set('sort_by','popularity.desc');url.searchParams.set('include_adult','false');url.searchParams.set('page',String(page));if(kind==='film')url.searchParams.set('region','FR');const result=await cachedJson<{results:Record<string,unknown>[];total_pages:number}>(`catalog-tmdb-${kind}-${page}`,url.toString(),6*60*60*1000);return{items:result.data.results.slice(0,limit).map(item=>normalizeTmdbCatalog(item,kind)),hasMore:page<result.data.total_pages,source:'TMDB',cachedAt:result.cachedAt,cacheState:result.state}}
async function tvmazeCatalog(page:number,limit:number):Promise<ProviderPage>{const offset=(page-1)*limit;const required=offset+limit;const all:Record<string,unknown>[]=[];const fetched:CachedResult<Record<string,unknown>[]>[]=[];for(let remotePage=0;all.length<required;remotePage++){const result=await cachedJson<Record<string,unknown>[]>(`catalog-tvmaze-${remotePage}`,`https://api.tvmaze.com/shows?page=${remotePage}`,12*60*60*1000);fetched.push(result);all.push(...result.data);if(!result.data.length)break}const selected=all.slice(offset,required);const items=await Promise.all(selected.map(async show=>{const id=Number(show.id);const image=show.image as {medium?:string;original?:string}|undefined;const rating=show.rating as {average?:number}|undefined;const runtime=show.averageRuntime??show.runtime;const premiered=String(show.premiered??'');const localized=await localizeTvmazeMetadata(normalizeTvmazeMetadata(show));return{id:`tvmaze-serie-${id}`,title:localized.title,kind:'serie' as const,year:Number(premiered.slice(0,4))||new Date().getFullYear(),genres:localized.genres??localizedTvmazeGenres(show.genres),duration:durationLabel(runtime,'serie'),rating:Number(rating?.average??0),quality:'1080p' as const,description:localized.overview??stripHtml(show.summary),palette:palette(id),symbol:'▥',art:image?.original??image?.medium,source:'tvmaze' as const,sourceUrl:localized.sourceUrl??String(show.url??''),informationSource:localized.informationSource??'TVmaze'}}));const cachedAt=fetched.map(result=>result.cachedAt).sort().at(-1)??new Date().toISOString();const states=[...new Set(fetched.map(result=>result.state))];return{items,hasMore:selected.length===limit&&fetched.at(-1)?.data.length!==0,source:'TVmaze + Wikipédia FR',cachedAt,cacheState:states.join('/')}}
type WikipediaPage={pageid:number;title:string;extract?:string;fullurl?:string;missing?:boolean;thumbnail?:{source?:string}};
type WikipediaResponse={query?:{pages?:Record<string,WikipediaPage>}};
function isFrenchSeriesPage(page:WikipediaPage,year?:number){const extract=page.extract??'';return !page.missing&&Boolean(extract)&&/(?:série|mini-série|feuilleton)\s+(?:télévisée|d'animation)|série d'animation/i.test(extract)&&(!year||extract.includes(String(year)))}
function cleanFrenchSeriesTitle(title:string){return title.replace(/\s*\((?:mini-)?série télévisée[^)]*\)$/i,'').trim()}
async function frenchSeriesInfo(title:string,year?:number):Promise<{title:string;overview:string;sourceUrl:string}|null>{const direct=new URL('https://fr.wikipedia.org/w/api.php');direct.searchParams.set('action','query');direct.searchParams.set('titles',`${title} (série télévisée)|${title}`);direct.searchParams.set('redirects','1');direct.searchParams.set('prop','extracts|info');direct.searchParams.set('inprop','url');direct.searchParams.set('exintro','1');direct.searchParams.set('explaintext','1');direct.searchParams.set('exchars','700');direct.searchParams.set('format','json');direct.searchParams.set('formatversion','2');const exact=await cachedJson<WikipediaResponse>(`metadata-wikipedia-fr-serie-direct-${slug(`${title}:${year??''}`)}`,direct.toString(),7*24*60*60*1000);let page=Object.values(exact.data.query?.pages??{}).find(candidate=>isFrenchSeriesPage(candidate,year));if(!page){const search=new URL('https://fr.wikipedia.org/w/api.php');search.searchParams.set('action','query');search.searchParams.set('generator','search');search.searchParams.set('gsrsearch',`intitle:"${title}" série télévisée${year?` ${year}`:''}`);search.searchParams.set('gsrnamespace','0');search.searchParams.set('gsrlimit','5');search.searchParams.set('prop','extracts|info');search.searchParams.set('inprop','url');search.searchParams.set('exintro','1');search.searchParams.set('explaintext','1');search.searchParams.set('exchars','700');search.searchParams.set('format','json');search.searchParams.set('formatversion','2');const fallback=await cachedJson<WikipediaResponse>(`metadata-wikipedia-fr-serie-search-${slug(`${title}:${year??''}`)}`,search.toString(),7*24*60*60*1000);const candidates=Object.values(fallback.data.query?.pages??{}).filter(candidate=>isFrenchSeriesPage(candidate,year));page=candidates.find(candidate=>comparableTitle(cleanFrenchSeriesTitle(candidate.title))===comparableTitle(title))}return page?.extract&&page.fullurl?{title:cleanFrenchSeriesTitle(page.title),overview:page.extract,sourceUrl:page.fullurl}:null}
async function localizeTvmazeMetadata(metadata:MediaMetadata){try{const french=await frenchSeriesInfo(metadata.title,Number(metadata.releaseDate?.slice(0,4))||undefined);return french?{...metadata,originalTitle:metadata.title,title:french.title,overview:french.overview,sourceUrl:french.sourceUrl,informationSource:'Wikipédia en français + TVmaze'}:metadata}catch(error){app.log.debug({error,title:metadata.title},'French series metadata unavailable');return metadata}}
async function wikipediaCatalog(page:number,limit:number):Promise<ProviderPage>{const years=[new Date().getFullYear(),new Date().getFullYear()-1];const requests=await Promise.all(years.map(async year=>{const url=new URL('https://en.wikipedia.org/w/api.php');url.searchParams.set('action','query');url.searchParams.set('generator','categorymembers');url.searchParams.set('gcmtitle',`Category:${year} films`);url.searchParams.set('gcmnamespace','0');url.searchParams.set('gcmtype','page');url.searchParams.set('gcmsort','timestamp');url.searchParams.set('gcmdir','desc');url.searchParams.set('gcmlimit','100');url.searchParams.set('prop','pageimages|extracts|info');url.searchParams.set('inprop','url');url.searchParams.set('piprop','thumbnail');url.searchParams.set('pithumbsize','780');url.searchParams.set('exintro','1');url.searchParams.set('explaintext','1');url.searchParams.set('exchars','420');url.searchParams.set('format','json');url.searchParams.set('formatversion','2');const result=await cachedJson<WikipediaResponse>(`catalog-wikipedia-en-films-v2-${year}`,url.toString(),24*60*60*1000);return{year,result}}));const all=requests.flatMap(({year,result})=>Object.values(result.data.query?.pages??{}).filter(item=>!/(?:box[ -]office|list of)/i.test(item.title)).map(item=>({year,item}))).sort((a,b)=>Number(Boolean(b.item.thumbnail))-Number(Boolean(a.item.thumbnail))||b.year-a.year||a.item.title.localeCompare(b.item.title,'en'));const offset=(page-1)*limit;const selected=all.slice(offset,offset+limit);const items=selected.map(({year,item})=>({id:`wikipedia-film-${item.pageid}`,title:item.title.replace(/\s*\((?:\d{4}\s+)?film\)$/i,''),kind:'film' as const,year,genres:['Cinéma'],duration:'Durée inconnue',rating:0,quality:'1080p' as const,description:item.extract??'Fiche encyclopédique Wikipédia.',palette:palette(item.pageid),symbol:'◉',art:item.thumbnail?.source,source:'wikipedia' as const,sourceUrl:item.fullurl}));return{items,hasMore:offset+limit<all.length,source:'Wikipédia',cachedAt:requests.map(x=>x.result.cachedAt).sort().at(-1)??new Date().toISOString(),cacheState:requests.every(x=>x.result.state==='hit')?'hit':requests.some(x=>x.result.state==='stale')?'stale':'miss'}}
async function catalogFor(kind:'film'|'serie',page:number,limit:number){if(process.env.TMDB_API_KEY)return tmdbCatalog(kind,page,limit);return kind==='serie'?tvmazeCatalog(page,limit):wikipediaCatalog(page,limit)}
function metadataToCatalogItem(item:MediaMetadata,kind:'film'|'serie',index:number):CatalogItem{const seed=Number(item.providerId)||parseInt(slug(String(item.providerId)),36)||index;return{id:`${item.provider}-${kind}-${item.providerId}`,title:item.title,kind,year:Number(item.releaseDate?.slice(0,4))||new Date().getFullYear(),genres:item.genres??[],duration:durationLabel(item.runtime,kind),rating:0,quality:'1080p',description:item.overview??'',palette:palette(seed),symbol:kind==='serie'?'▥':'◉',art:item.backdrop??item.poster,source:item.provider,sourceUrl:item.sourceUrl,informationSource:item.informationSource}}
async function searchedCatalog(query:string,kind?:'film'|'serie'):Promise<ProviderPage>{const kinds:('film'|'serie')[]=kind?[kind]:['film','serie'];const pages=await Promise.all(kinds.map(async mediaKind=>({mediaKind,result:await searchMetadata(query,mediaKind)})));return{items:pages.flatMap(({mediaKind,result})=>result.items.map((item,index)=>metadataToCatalogItem(item,mediaKind,index))),hasMore:false,source:[...new Set(pages.flatMap(page=>page.result.items.map(item=>item.informationSource??(item.provider==='tvmaze'?'TVmaze':item.provider==='wikipedia'?'Wikipédia':'TMDB'))))].join(' + ')||'Catalogue',cachedAt:new Date().toISOString(),cacheState:pages.map(page=>page.result.state).join('/')}}
function normalizeTvmazeMetadata(show:Record<string,unknown>):MediaMetadata{const image=show.image as {medium?:string;original?:string}|undefined;return{provider:'tvmaze',providerId:Number(show.id),title:String(show.name??''),overview:frenchTvmazeSummary(show),poster:image?.original??image?.medium,backdrop:image?.original,genres:localizedTvmazeGenres(show.genres),releaseDate:String(show.premiered??''),runtime:Number(show.averageRuntime??show.runtime??0)||undefined,sourceUrl:String(show.url??''),informationSource:'TVmaze · fiche technique en français'}}
function normalizeWikipediaMetadata(page:WikipediaPage,year?:number):MediaMetadata{return{provider:'wikipedia',providerId:page.pageid,title:page.title.replace(/\s*\((?:\d{4}\s+)?film\)$/i,''),overview:page.extract??'',poster:page.thumbnail?.source,backdrop:page.thumbnail?.source,genres:['Cinéma'],releaseDate:year?`${year}-01-01`:undefined,sourceUrl:page.fullurl}}
async function searchMetadata(query:string,kind:'film'|'serie',year?:string):Promise<{items:MediaMetadata[];state:string}>{
  const tmdbKey=process.env.TMDB_API_KEY;if(tmdbKey){const path=kind==='serie'?'tv':'movie';const url=new URL(`https://api.themoviedb.org/3/search/${path}`);url.searchParams.set('api_key',tmdbKey);url.searchParams.set('language','fr-FR');url.searchParams.set('query',query);if(year)url.searchParams.set(path==='tv'?'first_air_date_year':'year',year);const result=await cachedJson<{results:Array<Record<string,unknown>>}>(`metadata-search-${slug(`${path}:${query}:${year??''}`)}`,url.toString(),24*60*60*1000);return{items:result.data.results.slice(0,6).map(item=>normalizeTmdb(item,path)),state:result.state}}
  if(kind==='serie'){const url=`https://api.tvmaze.com/search/shows?q=${encodeURIComponent(query)}`;const result=await cachedJson<Array<{show:Record<string,unknown>}>>(`metadata-tvmaze-search-${slug(query)}`,url,24*60*60*1000);return{items:await Promise.all(result.data.slice(0,6).map(entry=>localizeTvmazeMetadata(normalizeTvmazeMetadata(entry.show)))),state:result.state}}
  const url=new URL('https://en.wikipedia.org/w/api.php');url.searchParams.set('action','query');url.searchParams.set('generator','search');url.searchParams.set('gsrsearch',`${query}${year?` ${year}`:''} film`);url.searchParams.set('gsrnamespace','0');url.searchParams.set('gsrlimit','6');url.searchParams.set('prop','pageimages|extracts|info');url.searchParams.set('inprop','url');url.searchParams.set('piprop','thumbnail');url.searchParams.set('pithumbsize','780');url.searchParams.set('exintro','1');url.searchParams.set('explaintext','1');url.searchParams.set('exchars','420');url.searchParams.set('format','json');url.searchParams.set('formatversion','2');const result=await cachedJson<WikipediaResponse>(`metadata-wikipedia-search-${slug(`${query}:${year??''}`)}`,url.toString(),24*60*60*1000);return{items:Object.values(result.data.query?.pages??{}).slice(0,6).map(page=>normalizeWikipediaMetadata(page,year?Number(year):undefined)),state:result.state}
}
async function fetchMetadata(provider:MediaMetadata['provider'],providerId:number|string,kind:'film'|'serie'):Promise<{metadata:MediaMetadata;state:string}>{
  if(provider==='tmdb'){const key=process.env.TMDB_API_KEY;if(!key)throw new Error('TMDB non configuré');const path=kind==='serie'?'tv':'movie';const url=`https://api.themoviedb.org/3/${path}/${providerId}?api_key=${encodeURIComponent(key)}&language=fr-FR`;const result=await cachedJson<Record<string,unknown>>(`metadata-tmdb-${path}-${providerId}`,url,7*24*60*60*1000);return{metadata:normalizeTmdb(result.data,path),state:result.state}}
  if(provider==='tvmaze'){const result=await cachedJson<Record<string,unknown>>(`metadata-tvmaze-show-${providerId}`,`https://api.tvmaze.com/shows/${providerId}`,7*24*60*60*1000);return{metadata:await localizeTvmazeMetadata(normalizeTvmazeMetadata(result.data)),state:result.state}}
  const url=new URL('https://en.wikipedia.org/w/api.php');url.searchParams.set('action','query');url.searchParams.set('pageids',String(providerId));url.searchParams.set('prop','pageimages|extracts|info');url.searchParams.set('inprop','url');url.searchParams.set('piprop','thumbnail');url.searchParams.set('pithumbsize','780');url.searchParams.set('exintro','1');url.searchParams.set('explaintext','1');url.searchParams.set('format','json');url.searchParams.set('formatversion','2');const result=await cachedJson<WikipediaResponse>(`metadata-wikipedia-page-${providerId}`,url.toString(),7*24*60*60*1000);const page=Object.values(result.data.query?.pages??{})[0];if(!page)throw new Error('Fiche Wikipédia introuvable');return{metadata:normalizeWikipediaMetadata(page),state:result.state}
}
function comparableTitle(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function groupLibrary(library:LibraryItem[]):LibraryGroup[]{const grouped=new Map<string,LibraryGroup>();for(const {path,...item} of library){const title=item.metadata?.title??item.title;const year=Number(item.metadata?.releaseDate?.slice(0,4))||item.year;const key=`${item.kind}:${comparableTitle(title)}:${year??''}`;const group=grouped.get(key)??{id:item.id,title,year,kind:item.kind,metadata:item.metadata,versions:[],totalSize:0,episodeCount:0};group.versions.push(item);group.totalSize+=item.size;if(item.episode)group.episodeCount++;grouped.set(key,group)}return[...grouped.values()]}
function groupForMedia(groups:LibraryGroup[],mediaId:string){return groups.find(group=>group.id===mediaId||group.versions.some(version=>version.id===mediaId))}
let enrichmentRunning=false;
async function enrichLibrary(limit=6){if(enrichmentRunning)return;enrichmentRunning=true;try{const db=loadDb();const pending=db.library.filter(item=>!item.metadata).slice(0,limit);let changed=false;for(const item of pending){try{const result=await searchMetadata(item.title,item.kind,item.year?String(item.year):undefined);const exact=result.items.filter(candidate=>comparableTitle(candidate.title)===comparableTitle(item.title)&&(!item.year||!candidate.releaseDate||Number(candidate.releaseDate.slice(0,4))===item.year));if(exact.length!==1)continue;const selected=exact[0];for(const sibling of db.library.filter(entry=>entry.kind===item.kind&&comparableTitle(entry.title)===comparableTitle(item.title))){sibling.metadata=selected;sibling.title=selected.title}changed=true}catch(error){app.log.warn({error,title:item.title},'Automatic metadata enrichment failed')}}if(changed)saveDb(db)}finally{enrichmentRunning=false}}
function slug(path: string) { let h=2166136261; for(const c of path) h=Math.imul(h^c.charCodeAt(0),16777619); return (h>>>0).toString(36); }
function titleFromFile(file: string) {
  const raw = parse(file).name.replace(/[._]/g,' ').replace(/\b(?:s\d{1,2}e\d{1,3}|\d{1,2}x\d{1,3}|season\s*\d+\s*episode\s*\d+)\b.*$/i,'').replace(/\b(19|20)\d{2}\b.*$/,'').replace(/\b(1080p|2160p|720p|bluray|webrip|web-dl).*$/i,'');
  return raw.replace(/\s+/g,' ').trim().replace(/\b\w/g,c=>c.toUpperCase());
}
function episodeFromFile(file:string){const name=parse(file).name;const m=name.match(/(?:S(\d{1,2})E(\d{1,3})|(\d{1,2})x(\d{1,3})|Season\s*(\d+)\s*Episode\s*(\d+))/i);return m?{season:Number(m[1]??m[3]??m[5]),episode:Number(m[2]??m[4]??m[6])}:null}
async function probe(path:string){try{const {stdout}=await execFileAsync('ffprobe',['-v','quiet','-print_format','json','-show_format','-show_streams',path],{timeout:15000,maxBuffer:2_000_000});const data=JSON.parse(stdout);const video=data.streams?.find((s:{codec_type:string})=>s.codec_type==='video');const audio=data.streams?.filter((s:{codec_type:string})=>s.codec_type==='audio')??[];const subtitles=data.streams?.filter((s:{codec_type:string})=>s.codec_type==='subtitle')??[];return{duration:Number(data.format?.duration??0),videoCodec:video?.codec_name,width:video?.width,height:video?.height,hdr:/smpte2084|arib-std-b67/i.test(JSON.stringify(video)),audio:audio.map((s:{codec_name:string;channels:number;tags?:{language?:string}})=>({codec:s.codec_name,channels:s.channels,language:s.tags?.language})),subtitles:subtitles.map((s:{codec_name:string;tags?:{language?:string}})=>({codec:s.codec_name,language:s.tags?.language}))}}catch{return{probePending:true}}}
async function walk(root: string): Promise<string[]> {
  if (!existsSync(root)) return [];
  const out: string[]=[]; for(const entry of await readdir(root,{withFileTypes:true})) { const p=join(root,entry.name); if(entry.isDirectory()) out.push(...await walk(p)); else if(videoExt.has(extname(p).toLowerCase())) out.push(p); } return out;
}
async function scanLibrary() {
  const files=(await Promise.all(mediaRoots.map(walk))).flat();
  const db=loadDb();const previous=new Map(db.library.map(item=>[item.path,item]));
  const library: LibraryItem[]=[]; for(const path of files){const info=statSync(path);const old=previous.get(path);const match=parse(path).name.match(/\b((?:19|20)\d{2})\b/);const ep=episodeFromFile(path);const unchanged=old&&old.size===info.size&&old.modifiedAt===info.mtime.toISOString();library.push({id:slug(path),title:old?.metadata?.title??titleFromFile(path),path,kind:ep?'serie':'film',year:match?Number(match[1]):old?.year,...(ep??{}),size:info.size,modifiedAt:info.mtime.toISOString(),addedAt:info.birthtime.toISOString(),technical:unchanged?old.technical:await probe(path),metadata:old?.metadata})}
  db.library=library;saveDb(db);void enrichLibrary(6);return library;
}

await app.register(cors, { origin: true });
app.get('/api/health', async () => ({ ok:true, version:'0.1.0', mediaRoots }));
app.get('/api/profiles',async()=>loadDb().profiles.map(({pinHash,...profile})=>({...profile,locked:Boolean(pinHash)})));
app.post<{Body:{name:string;ageLimit:number;avatar?:string;accent?:string;pin?:string}}>('/api/profiles',async(request,reply)=>{const name=request.body.name?.trim();if(!name)return reply.code(400).send({error:'Le nom est obligatoire'});const db=loadDb();const profile:ProfileRecord={id:randomUUID(),name,ageLimit:Math.max(0,Math.min(18,Number(request.body.ageLimit??18))),avatar:safeAvatar(request.body.avatar,name[0].toUpperCase()),accent:safeAccent(request.body.accent),createdAt:new Date().toISOString(),pinHash:request.body.pin?hashPin(request.body.pin):undefined};db.profiles.push(profile);saveDb(db);const{pinHash,...safe}=profile;return reply.code(201).send({...safe,locked:Boolean(pinHash)})});
app.put<{Params:{id:string};Body:{name:string;ageLimit:number;avatar?:string;accent?:string;pin?:string|null}}>('/api/profiles/:id',async(request,reply)=>{const name=request.body.name?.trim();if(!name)return reply.code(400).send({error:'Le nom est obligatoire'});const db=loadDb();let profile=db.profiles.find(item=>item.id===request.params.id);if(!profile){profile={id:request.params.id,name,ageLimit:18,avatar:name[0].toUpperCase(),accent:'#22d3ee',createdAt:new Date().toISOString()};db.profiles.push(profile)}profile.name=name;profile.ageLimit=Math.max(0,Math.min(18,Number(request.body.ageLimit??profile.ageLimit)));profile.avatar=safeAvatar(request.body.avatar,profile.avatar||name[0].toUpperCase());profile.accent=safeAccent(request.body.accent??profile.accent);if(request.body.pin===null||request.body.pin==='')delete profile.pinHash;else if(request.body.pin!==undefined)profile.pinHash=hashPin(request.body.pin);saveDb(db);const{pinHash,...safe}=profile;return{...safe,locked:Boolean(pinHash)}});
app.post<{Params:{id:string};Body:{pin:string}}>('/api/profiles/:id/unlock',async(request,reply)=>{const profile=loadDb().profiles.find(p=>p.id===request.params.id);if(!profile)return reply.code(404).send({error:'Profil introuvable'});if(!profile.pinHash)return{ok:true};return verifyPin(request.body.pin??'',profile.pinHash)?{ok:true}:reply.code(401).send({error:'Code incorrect'})});
app.get('/api/library', async () => loadDb().library.map(({path,...item})=>item));
app.get('/api/library/grouped', async () => groupLibrary(loadDb().library).sort((a,b)=>b.versions[0].addedAt.localeCompare(a.versions[0].addedAt)));
app.get<{Params:{id:string};Querystring:{profileId?:string}}>('/api/library/group/:id',async(request,reply)=>{const db=loadDb();const group=groupForMedia(groupLibrary(db.library),request.params.id);if(!group)return reply.code(404).send({error:'Média introuvable'});const profileId=request.query.profileId;const progressFor=(id:string)=>{if(!profileId)return{position:0,progress:0};const entry=playbackEntry(db.playback[`${profileId}:${id}`]);return entry?{position:entry.position,progress:entry.duration>0?entry.position/entry.duration:0}:{position:0,progress:0}};const versions=group.versions.map(version=>({...version,...progressFor(version.id)}));const episodes=versions.filter(version=>version.episode).sort((a,b)=>(a.season??0)-(b.season??0)||(a.episode??0)-(b.episode??0));const nextEpisode=episodes.find(episode=>episode.progress<0.9)??episodes[0];return{...group,versions,nextEpisodeId:nextEpisode?.id};});
app.post('/api/library/scan', async () => ({ items: await scanLibrary() }));
app.post('/api/library/enrich',async()=>{void enrichLibrary(30);return{ok:true,status:'started'}});
app.get<{Querystring:{kind?:'film'|'serie';page?:string;limit?:string;genre?:string;q?:string}}>('/api/catalog',async(request,reply)=>{const page=Math.max(1,Number(request.query.page??1));const limit=Math.max(1,Math.min(30,Number(request.query.limit??12)));try{let result:ProviderPage;if(request.query.q?.trim()){result=page===1?await searchedCatalog(request.query.q.trim(),request.query.kind):{items:[],hasMore:false,source:'Catalogue',cachedAt:new Date().toISOString(),cacheState:'hit'}}else if(request.query.kind){result=await catalogFor(request.query.kind,page,limit)}else{const filmLimit=Math.ceil(limit/2);const serieLimit=limit-filmLimit;const[films,series]=await Promise.all([catalogFor('film',page,filmLimit),catalogFor('serie',page,serieLimit)]);const items:CatalogItem[]=[];for(let index=0;index<Math.max(films.items.length,series.items.length);index++){if(films.items[index])items.push(films.items[index]);if(series.items[index])items.push(series.items[index])}result={items:items.slice(0,limit),hasMore:films.hasMore||series.hasMore,source:`${films.source} + ${series.source}`,cachedAt:films.cachedAt>series.cachedAt?films.cachedAt:series.cachedAt,cacheState:films.cacheState===series.cacheState?films.cacheState:`${films.cacheState}/${series.cacheState}`}}const wantedGenre=request.query.genre?.trim().toLocaleLowerCase('fr');const items=result.items.filter(item=>!wantedGenre||item.genres.some(genre=>genre.toLocaleLowerCase('fr')===wantedGenre));reply.header('Cache-Control','private, max-age=600, stale-while-revalidate=3600').header('X-SceneRoot-Cache',result.cacheState);return{items:items.slice(0,limit),page,hasMore:result.hasMore,source:result.source,cachedAt:result.cachedAt}}catch(error){app.log.warn({error},'Catalog loading failed');return reply.code(502).send({error:'Catalogue distant temporairement indisponible'})}});
app.get<{Querystring:{q:string;kind?:'film'|'serie';year?:string}}>('/api/metadata/search',async(request,reply)=>{if(!request.query.q)return reply.code(400).send({error:'Recherche manquante'});try{const result=await searchMetadata(request.query.q,request.query.kind??'film',request.query.year);reply.header('X-SceneRoot-Cache',result.state);return result.items}catch(error){app.log.warn({error},'Metadata search failed');return reply.code(502).send({error:'Source de métadonnées indisponible'})}});
app.put<{Params:{id:string};Body:{provider?:MediaMetadata['provider'];providerId:number|string}}>('/api/library/:id/match',async(request,reply)=>{const db=loadDb();const item=db.library.find(x=>x.id===request.params.id);if(!item)return reply.code(404).send({error:'Média introuvable'});try{const result=await fetchMetadata(request.body.provider??'tmdb',request.body.providerId,item.kind);const originalTitle=item.title;for(const sibling of db.library.filter(entry=>entry.kind===item.kind&&comparableTitle(entry.title)===comparableTitle(originalTitle))){sibling.metadata=result.metadata;sibling.title=result.metadata.title}saveDb(db);reply.header('X-SceneRoot-Cache',result.state);return result.metadata}catch(error){app.log.warn({error},'Metadata match failed');return reply.code(502).send({error:'Correspondance indisponible'})}});
app.get('/api/storage',async()=>mediaRoots.filter(existsSync).map(root=>{const s=statfsSync(root);return{root,total:s.blocks*s.bsize,free:s.bfree*s.bsize,available:s.bavail*s.bsize,libraryBytes:loadDb().library.filter(x=>isWithin(root,x.path)).reduce((n,x)=>n+x.size,0)}}));
app.get<{Params:{id:string}}>('/api/media/:id', async (request, reply) => {
  const item=loadDb().library.find(x=>x.id===request.params.id); if(!item) return reply.code(404).send({error:'Média introuvable'});
  if(!isWithinRoots(item.path)) return reply.code(403).send({error:'Chemin non autorisé'});
  const total=statSync(item.path).size; const range=request.headers.range; const contentType=mimeFor(item.path);
  if(!range){reply.header('Content-Length',total).header('Accept-Ranges','bytes').header('Content-Type',contentType);return reply.send(createReadStream(item.path));}
  const [startRaw,endRaw]=range.replace(/bytes=/,'').split('-'); const start=Number(startRaw); const end=endRaw?Number(endRaw):Math.min(start+8*1024*1024,total-1);
  reply.code(206).headers({'Content-Range':`bytes ${start}-${end}/${total}`,'Accept-Ranges':'bytes','Content-Length':end-start+1,'Content-Type':contentType});
  return reply.send(createReadStream(item.path,{start,end}));
});
app.post<{Body:Rating}>('/api/ratings', async request => { const db=loadDb(); const rating={...request.body,at:new Date().toISOString()}; db.ratings=db.ratings.filter(x=>!(x.profileId===rating.profileId&&x.mediaId===rating.mediaId));db.ratings.push(rating);saveDb(db);return rating; });
app.put<{Params:{profileId:string;mediaId:string};Body:{position:number;duration?:number}}>('/api/playback/:profileId/:mediaId', async request=>{const db=loadDb();db.playback[`${request.params.profileId}:${request.params.mediaId}`]={position:Number(request.body.position)||0,duration:Number(request.body.duration)||0,updatedAt:new Date().toISOString()};saveDb(db);return{ok:true}});
app.get<{Params:{profileId:string}}>('/api/playback/:profileId',async request=>{const db=loadDb();const groups=groupLibrary(db.library);const prefix=`${request.params.profileId}:`;return Object.entries(db.playback).filter(([key])=>key.startsWith(prefix)).map(([key,value])=>{const entry=playbackEntry(value);if(!entry)return null;const mediaId=key.slice(prefix.length);const group=groupForMedia(groups,mediaId);if(!group)return null;const progress=entry.duration>0?entry.position/entry.duration:0;return{group,mediaId,position:entry.position,duration:entry.duration,progress,updatedAt:entry.updatedAt,completed:progress>=0.92}}).filter((entry): entry is NonNullable<typeof entry>=>entry!==null&&!entry.completed).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))});
app.get<{Params:{profileId:string}}>('/api/history/:profileId',async request=>{const db=loadDb();const groups=groupLibrary(db.library);const prefix=`${request.params.profileId}:`;const seen=new Map<string,{group:LibraryGroup;mediaId:string;progress:number;position:number;duration:number;updatedAt:string;completed:boolean;rating?:number;tags?:string[]}>();for(const[key,value]of Object.entries(db.playback)){if(!key.startsWith(prefix))continue;const entry=playbackEntry(value);if(!entry)continue;const mediaId=key.slice(prefix.length);const group=groupForMedia(groups,mediaId);if(!group)continue;const progress=entry.duration>0?entry.position/entry.duration:0;seen.set(group.id,{group,mediaId,progress,position:entry.position,duration:entry.duration,updatedAt:entry.updatedAt,completed:progress>=0.92})}for(const rating of db.ratings.filter(r=>r.profileId===request.params.profileId)){const group=groupForMedia(groups,rating.mediaId);if(!group)continue;const existing=seen.get(group.id);if(existing){existing.rating=rating.score;existing.tags=rating.tags;if(rating.at>existing.updatedAt)existing.updatedAt=rating.at}else seen.set(group.id,{group,mediaId:rating.mediaId,progress:0,position:0,duration:0,updatedAt:rating.at,completed:true,rating:rating.score,tags:rating.tags})}return[...seen.values()].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))});
app.get<{Params:{profileId:string}}>('/api/ratings/:profileId',async request=>loadDb().ratings.filter(rating=>rating.profileId===request.params.profileId));
app.post<{Body:{profileIds:string[];candidates:Array<{id:string;genres:string[];ageRating?:number}>;preferUnseen?:boolean}}>('/api/recommendations/group',async request=>{
  const db=loadDb();const{profileIds,candidates}=request.body;const preferUnseen=request.body.preferUnseen!==false;
  const groups=groupLibrary(db.library);
  const genresOfMedia=(mediaId:string):string[]=>{const inCandidate=candidates.find(candidate=>candidate.id===mediaId);if(inCandidate?.genres?.length)return inCandidate.genres;return groupForMedia(groups,mediaId)?.metadata?.genres??[]};
  const profileTaste=new Map<string,Record<string,{sum:number;weight:number}>>();const seenByProfile=new Map<string,Set<string>>();
  for(const profileId of profileIds){
    const taste:Record<string,{sum:number;weight:number}>={};const seen=new Set<string>();
    for(const rating of db.ratings.filter(r=>r.profileId===profileId)){const value=Math.max(0,Math.min(100,rating.score*10));for(const genre of genresOfMedia(rating.mediaId)){const t=taste[genre]??{sum:0,weight:0};t.sum+=value;t.weight+=1;taste[genre]=t}seen.add(rating.mediaId)}
    for(const[key,raw]of Object.entries(db.playback)){if(!key.startsWith(`${profileId}:`))continue;const mediaId=key.slice(profileId.length+1);const entry=playbackEntry(raw);if(!entry)continue;const progress=entry.duration>0?entry.position/entry.duration:0;if(progress<0.9)continue;seen.add(mediaId);if(!db.ratings.some(r=>r.profileId===profileId&&r.mediaId===mediaId))for(const genre of genresOfMedia(mediaId)){const t=taste[genre]??{sum:0,weight:0};t.sum+=75;t.weight+=0.5;taste[genre]=t}}
    profileTaste.set(profileId,taste);seenByProfile.set(profileId,seen);
  }
  const genreAffinity=(profileId:string,genre:string)=>{const t=profileTaste.get(profileId)?.[genre];return t&&t.weight>0?t.sum/t.weight:65};
  const predict=(profileId:string,candidate:{id:string;genres:string[]})=>{const rating=db.ratings.find(r=>r.profileId===profileId&&r.mediaId===candidate.id);if(rating)return Math.max(0,Math.min(100,rating.score*10));const genres=candidate.genres?.length?candidate.genres:['(inconnu)'];return genres.map(genre=>genreAffinity(profileId,genre)).reduce((a,b)=>a+b,0)/genres.length};
  const profileById=new Map(db.profiles.map(profile=>[profile.id,profile]));
  return candidates.map(candidate=>{
    const affinities=profileIds.map(profileId=>Math.round(predict(profileId,candidate)));
    const average=affinities.reduce((a,b)=>a+b,0)/Math.max(1,affinities.length);
    const disagreement=affinities.length?Math.max(...affinities)-Math.min(...affinities):0;
    const seenBy=profileIds.filter(profileId=>seenByProfile.get(profileId)?.has(candidate.id));
    let score=average-0.42*disagreement;if(preferUnseen&&seenBy.length)score-=12*(seenBy.length/Math.max(1,profileIds.length));
    let allowed=true;if(typeof candidate.ageRating==='number')for(const profileId of profileIds){const limit=profileById.get(profileId)?.ageLimit;if(typeof limit==='number'&&candidate.ageRating>limit)allowed=false}
    return{id:candidate.id,score:Math.round(score),average:Math.round(average),disagreement:Math.round(disagreement),affinities,seenBy,allowed};
  }).filter(candidate=>candidate.allowed).sort((a,b)=>b.score-a.score);
});
app.post<{Body:{ttl:'shutdown'|'24h'|'7d'|'permanent';ageLimit:number}}>('/api/guests',async request=>({id:`guest-${Date.now()}`,temporary:request.body.ttl!=='permanent',expiresAt:request.body.ttl==='24h'?Date.now()+86400000:request.body.ttl==='7d'?Date.now()+604800000:null,ageLimit:request.body.ageLimit}));

function sources():Source[]{const configured:Source[]=[];if(process.env.C411_API_KEY)configured.push({id:'c411',name:'C411',url:'https://c411.org/api/torznab',apiKey:process.env.C411_API_KEY,categories:'2000,5000'});try{configured.push(...JSON.parse(process.env.SCENEROOT_TORZNAB_SOURCES??'[]'))}catch{}return configured}
function xmlText(block:string,tag:string){const m=block.match(new RegExp(`<${tag}[^>]*>(?:<!\\[CDATA\\[)?([\\s\\S]*?)(?:\\]\\]>)?</${tag}>`,'i'));return m?.[1]?.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
app.get<{Querystring:{q:string;kind?:'movie'|'tv';season?:string;episode?:string}}>('/api/sources/search',async(request,reply)=>{if(!request.query.q)return reply.code(400).send({error:'Recherche manquante'});const results=[];for(const source of sources()){const url=new URL(source.url);url.searchParams.set('apikey',source.apiKey);url.searchParams.set('t',request.query.kind==='tv'?'tvsearch':request.query.kind==='movie'?'movie':'search');url.searchParams.set('q',request.query.q);if(source.categories)url.searchParams.set('cat',source.categories);if(request.query.season)url.searchParams.set('season',request.query.season);if(request.query.episode)url.searchParams.set('ep',request.query.episode);try{const res=await fetch(url,{signal:AbortSignal.timeout(10000)});const xml=await res.text();for(const block of xml.match(/<item>[\s\S]*?<\/item>/gi)??[]){results.push({source:source.name,title:xmlText(block,'title'),link:xmlText(block,'link')??xmlText(block,'guid'),size:Number(xmlText(block,'size')??0),seeders:Number(block.match(/name="seeders"[^>]*value="(\d+)"/i)?.[1]??0),published:xmlText(block,'pubDate')})}}catch(error){app.log.warn({source:source.name,error},'Torznab source failed')}}return results});

app.post<{Body:{magnet:string;expectedBytes?:number}}>('/api/downloads', async (request,reply)=>{
  if(!request.body.magnet?.startsWith('magnet:?')) return reply.code(400).send({error:'Lien magnet invalide'});
  const targetRoot=mediaRoots.find(existsSync)??dataDir;const disk=statfsSync(targetRoot);const available=disk.bavail*disk.bsize;const reserve=Number(process.env.SCENEROOT_MIN_FREE_GB??50)*1024**3;if(available-(request.body.expectedBytes??0)<reserve)return reply.code(507).send({error:'Espace disque insuffisant',available,reserve,expectedBytes:request.body.expectedBytes??0});
  const rpc=process.env.TRANSMISSION_RPC_URL; if(!rpc) return reply.code(503).send({error:'Configurez TRANSMISSION_RPC_URL'});
  const auth=process.env.TRANSMISSION_RPC_AUTH; const headers:Record<string,string>={'Content-Type':'application/json'}; if(auth)headers.Authorization=`Basic ${Buffer.from(auth).toString('base64')}`;
  let response=await fetch(rpc,{method:'POST',headers,body:JSON.stringify({method:'torrent-add',arguments:{filename:request.body.magnet}})});
  if(response.status===409){headers['X-Transmission-Session-Id']=response.headers.get('x-transmission-session-id')??'';response=await fetch(rpc,{method:'POST',headers,body:JSON.stringify({method:'torrent-add',arguments:{filename:request.body.magnet}})});}
  return reply.code(response.ok?200:502).send(await response.json());
});
app.post<{Body:{kind:'film'|'serie';preferredQuality?:string;preferredLanguages?:string[];preferHdr?:boolean;maxBytes?:number;candidates:Array<{id:string;title:string;quality:string;languages:string[];hdr:boolean;size:number;seeders:number;codec?:string}>}}>('/api/downloads/rank',async request=>request.body.candidates.map(candidate=>{let score=Math.min(30,Math.log2(candidate.seeders+1)*5);if(candidate.quality===request.body.preferredQuality)score+=28;if(request.body.preferredLanguages?.some(l=>candidate.languages.includes(l)))score+=22;if(request.body.preferHdr&&candidate.hdr)score+=10;if(request.body.maxBytes&&candidate.size>request.body.maxBytes)score-=35;if(/hevc|h265/i.test(candidate.codec??''))score+=6;return{...candidate,compatibilityScore:Math.round(score)}}).sort((a,b)=>b.compatibilityScore-a.compatibilityScore));
app.post('/api/cec/:action', async (request,reply)=>{
  const action=(request.params as {action:string}).action; const commands:Record<string,string>={active:'as',standby:'tx 10:36',scan:'scan'}; if(!commands[action])return reply.code(400).send({error:'Action CEC inconnue'});
  const child=spawn('cec-client',commands[action].split(' '),{stdio:'ignore'}); child.on('error',()=>{}); return {ok:true};
});
app.post<{Params:{id:string};Body:{startPosition?:number}}>('/api/player/:id/play',async(request,reply)=>{const item=loadDb().library.find(x=>x.id===request.params.id);if(!item)return reply.code(404).send({error:'Média introuvable'});if(!isWithinRoots(item.path))return reply.code(403).send({error:'Chemin non autorisé'});mpvProcess?.kill();const start=Number(request.body?.startPosition);const args=['--fs','--hwdec=auto-safe','--audio-display=no','--keep-open=no',`--input-ipc-server=${mpvSocket}`];if(start>0)args.push(`--start=${Math.floor(start)}`);args.push(item.path);mpvProcess=spawn('mpv',args,{stdio:'ignore',env:{...process.env,DISPLAY:process.env.DISPLAY??':0'}});mpvProcess.on('exit',()=>{mpvProcess=null});mpvProcess.on('error',error=>app.log.warn({error},'mpv failed'));return{ok:true,engine:'mpv',mediaId:item.id}});
type MpvTrack={id:number;type:string;title?:string;lang?:string;selected?:boolean;'external-filename'?:string};
app.get('/api/player/status',async(_request,reply)=>{if(!mpvProcess)return{engine:'mpv' as const,running:false};try{const[position,duration,pause,tracks,title,path]=await Promise.all([mpvGet<number>('time-pos'),mpvGet<number>('duration'),mpvGet<boolean>('pause'),mpvGet<MpvTrack[]>('track-list'),mpvGet<string>('media-title'),mpvGet<string>('path')]);const mapTracks=(type:string)=>(tracks??[]).filter(track=>track.type===type).map(track=>({id:track.id,label:track.title||track.lang||(track['external-filename']?'Fichier externe':`Piste ${track.id}`),lang:track.lang,selected:Boolean(track.selected)}));return{engine:'mpv' as const,running:true,playing:pause===false,position:position??0,duration:duration??0,title:title??undefined,path:path??undefined,audioTracks:mapTracks('audio'),subtitleTracks:mapTracks('sub')}}catch{return reply.code(503).send({engine:'mpv',running:false,error:'Lecteur mpv indisponible'})}});
app.post<{Body:{command:string;value?:number|string}}>('/api/player/control',async(request,reply)=>{const{command,value}=request.body;let mpvCmd:unknown[]|undefined={pause:['cycle','pause'],play:['set_property','pause',false],stop:['quit'],'seek-forward':['seek',30,'relative'],'seek-back':['seek',-10,'relative'],'audio-next':['cycle','audio'],'subtitle-next':['cycle','sub']}[command];if(command==='seek-to'&&typeof value==='number')mpvCmd=['seek',value,'absolute'];else if(command==='set-audio')mpvCmd=['set_property','aid',value??'auto'];else if(command==='set-subtitle')mpvCmd=['set_property','sid',value===undefined||value==='no'?'no':value];if(!mpvCmd)return reply.code(400).send({error:'Commande inconnue'});try{await mpvCommand(mpvCmd);return{ok:true}}catch{return reply.code(503).send({error:'Lecteur mpv indisponible'})}});

const dist=resolve('./dist');
if(existsSync(dist)){
  await app.register(staticPlugin,{root:dist});
  app.setNotFoundHandler((request,reply)=>request.url.startsWith('/api/')?reply.code(404).send({error:'Route inconnue'}):reply.sendFile('index.html'));
}
await app.listen({port,host:'0.0.0.0'});
if(process.env.SCENEROOT_WATCH!=='false'){scanLibrary().catch(error=>app.log.warn({error},'Initial media scan failed'));setInterval(()=>scanLibrary().catch(error=>app.log.warn({error},'Background media scan failed')),60_000).unref()}
