import { Lock, Pencil, Save, ShieldOff, Trash2, UserPlus, X } from 'lucide-react';
import { useState } from 'react';
import { accentForAvatar, avatarChoices } from '../data/avatars';
import type { Profile } from '../types';
import { useEscapeClose } from '../hooks/useEscapeClose';

export function ProfileEditor({profile,onClose,onSaved,onDeleted,deletable}:{profile?:Profile;onClose:()=>void;onSaved:(profile:Profile)=>void;onDeleted?:(profile:Profile)=>void;deletable?:boolean}) {
  useEscapeClose(onClose);
  const[name,setName]=useState(profile?.name??'');const[age,setAge]=useState(profile?.ageLimit??18);const[avatar,setAvatar]=useState(profile?.avatar?.startsWith('/assets/avatars/')?profile.avatar:avatarChoices[0].src);const[pin,setPin]=useState('');const[removePin,setRemovePin]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[deleting,setDeleting]=useState(false);
  const remove=async()=>{if(!profile||!onDeleted)return;if(!window.confirm(`Supprimer le profil « ${profile.name} » ? Son historique et ses notes seront effacés.`))return;setDeleting(true);setError('');try{const response=await fetch(`/api/profiles/${profile.id}`,{method:'DELETE'});if(!response.ok)throw new Error('Suppression impossible');onDeleted(profile)}catch(cause){setError((cause as Error).message);setDeleting(false)}};
  const submit=async()=>{const clean=name.trim();if(!clean){setError('Saisissez un nom.');return}setSaving(true);setError('');const body:Record<string,unknown>={name:clean,ageLimit:age,avatar,accent:accentForAvatar(avatar)};if(pin)body.pin=pin;else if(removePin)body.pin=null;try{const response=await fetch(profile?`/api/profiles/${profile.id}`:'/api/profiles',{method:profile?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as Profile&{error?:string};if(!response.ok)throw new Error(result.error||'Enregistrement impossible');onSaved(result)}catch(cause){setError((cause as Error).message)}finally{setSaving(false)}};
  return <div className="modal-backdrop"><div className="profile-modal profile-editor"><button className="modal-close" onClick={onClose}><X/></button><span className="modal-icon">{profile?<Pencil/>:<UserPlus/>}</span><h2>{profile?'Modifier le profil':'Nouveau profil'}</h2><p>{profile?'Personnalisez ce profil sans perdre son historique.':'Créez un espace personnel avec ses propres recommandations.'}</p><div className="profile-fields"><label>Nom<input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder="Prénom" maxLength={32}/></label><label>Limite d’âge<select value={age} onChange={event=>setAge(Number(event.target.value))}><option value="18">Tout public</option><option value="10">-10</option><option value="13">-13</option><option value="16">-16</option></select></label></div><fieldset className="avatar-picker"><legend>Choisissez un avatar</legend><div>{avatarChoices.map(choice=><button type="button" className={avatar===choice.src?'selected':''} key={choice.id} onClick={()=>setAvatar(choice.src)} title={choice.label}><img src={choice.src} alt={choice.label} loading="lazy" decoding="async"/><span>{choice.label}</span></button>)}</div></fieldset><label className="pin-field"><Lock/>Code de verrouillage<input type="password" inputMode="numeric" value={pin} onChange={event=>{setPin(event.target.value.replace(/\D/g,'').slice(0,8));setRemovePin(false)}} placeholder={profile?.locked?'Laisser vide pour conserver':'Optionnel'} /></label>{profile?.locked&&<button className={`remove-pin ${removePin?'selected':''}`} type="button" onClick={()=>{setRemovePin(value=>!value);setPin('')}}><ShieldOff/>{removePin?'Le code sera supprimé':'Supprimer le code actuel'}</button>}{error&&<div className="profile-error">{error}</div>}<button className="primary modal-submit" onClick={()=>void submit()} disabled={saving||deleting}><Save/>{saving?'Enregistrement…':profile?'Enregistrer les modifications':'Créer le profil'}</button>{profile&&deletable&&onDeleted&&<button className="remove-profile" type="button" onClick={()=>void remove()} disabled={deleting||saving}><Trash2/>{deleting?'Suppression…':'Supprimer ce profil'}</button>}</div></div>;
}
